'use strict';
const G = require('../src/game');
const W = require('../src/world');
(async () => {
  const cfg = { llm: { baseURL: '', apiKey: '', model: '' } };
  const d = W.buildDemoWorld();
  let r;
  r = await G.runTurn(d, '我要去省城', cfg);
  console.log('[1] 计划 intent=', r.intent.kind, '| 计划=', JSON.stringify(d.plans.map(p => ({ dest: p.dest, status: p.status, ticket: p.ticket }))));
  r = await G.runTurn(d, '买票', cfg);
  console.log('[2] 不在车站买票→', r.intent.kind, '| 提示=', d.sceneLog.slice(-1)[0].text.slice(0, 40));
  r = await G.runTurn(d, '去镇汽车站', cfg);
  console.log('[3] 到车站→', r.view.plans.slice(-1)[0].dest, '（待买票）');
  r = await G.runTurn(d, '买票', cfg);
  console.log('[4] 买票 → cash=', r.view.money.cash, '| ticket=', d.plans.slice(-1)[0].ticket, '| 提示=', d.sceneLog.slice(-1)[0].text.slice(0, 40));
  r = await G.runTurn(d, '我出发', cfg);
  console.log('[5] 上车 → status=', d.plans.slice(-1)[0].status, '| pendingBuild=', (d.current.pendingBuilds || []).length, '| beats尾=', (r.frame.beats || []).slice(-1)[0].text.slice(0, 30));
  r = await G.runTurn(d, '等1小时', cfg);
  console.log('[6] 1小时内 → status=', d.plans.slice(-1)[0].status, '| pending=', (d.current.pendingBuilds || []).length, '| 折返了吗=', d.plans.slice(-1)[0].status === 'blocked');
  r = await G.runTurn(d, '等8小时', cfg);
  console.log('[7] 到站 → status=', d.plans.slice(-1)[0].status, '| 场景=', d.current.sceneId, '| 城市单位=', Object.keys(d.entities).filter(k => k.indexOf('city1_') === 0).length, '| 新闻=', d.news.slice(-2).map(n => n.title).join(' / '));
  const v = G.buildView(d);
  console.log('[8] 地图已见=', v.map.map(m => m.name).join(','), '| 玩家=', v.me.identity.姓名 || v.playerName, '| plans=', JSON.stringify(v.plans.slice(-1)));
  r = await G.runTurn(d, '去街口招待所', cfg);
  console.log('[9] 城市内部移动 →', r.view.place.name, '| 在场=', r.view.cast.map(c => c.name).join(','), '| marks=', r.view.artMarks.length);
  r = await G.runTurn(d, '和修鞋匠说说话', cfg);
  console.log('[10] 跟城市NPC搭话 → intent=', r.intent.kind, '| beats=', (r.frame.beats || []).length);
  r = await G.runTurn(d, '回青石镇', cfg);
  console.log('[11] 回程 →', r.view.place.name, '| (坐车回=去车站再走)');
})();
